import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/NavBar";
import Main from "../components/Main";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Avijit | FE Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Main />
      <About />
      <Skills />
      <Projects />
    </div>
  );
}
